POST http://localhost:8088/data-generator/
Content-Type: application/json

{
  "numAccounts": 1,
  "minInteractions": 3,
  "maxInteractions": 6
}

###

GET http://localhost:8088/bankaccount/7f885699-d98a-4685-bd2c-1e699e85a2c5
Content-Type: application/json
