POST http://localhost:8080/data-generator/
Content-Type: application/json

{
  "numAccounts": 100,
  "minInteractions": 20,
  "maxInteractions": 40
}

###

GET http://localhost:8080/bankaccount/55b99080-7753-4231-9a38-9d373ba458cc
Content-Type: application/json
