### create bank account
PUT http://localhost:8088/bankaccount?owner=Heinz

> {%
  client.global.set("bankAccountId", response.body.trim());
%}

### get current balance
GET http://localhost:8088/bankaccount/{{bankAccountId}}/balance
Content-Type: application/json

### get current owner
GET http://localhost:8088/bankaccount/{{bankAccountId}}/owner
Content-Type: application/json

### deposit money
POST http://localhost:8088/bankaccount/{{bankAccountId}}/deposit?euroInCent=1000

### withdraw money
POST http://localhost:8088/bankaccount/{{bankAccountId}}/withdraw?euroInCent=500

### change owner
POST http://localhost:8088/bankaccount/{{bankAccountId}}/change-owner?newOwner=Harald
